### ISSUE TITLE
Update Link to Mailing List

### ISSUE THREAD

**Issue by stephskardal** [openannotation/annotatorjs.org#10]
From @tilgovi: 

I few weeks ago a put in a request to gmane.org, a popular mailing list and newsgroup archive for free and open source software projects and related topics.

This list is now archived here: http://dir.gmane.org/gmane.comp.web.annotator

I've also submitted a request to have the archives ingested, but that appears not to have happened yet.

Folks involved in improving annotatorjs.org, you may wish to link here. It is less apparent to me how one subscribes here vs the official home of the list, so you may wish to link to both?

Here's that link: https://lists.okfn.org/mailman/listinfo/annotator-dev

**Comment by tilgovi** [comment]
Site is Jekyll-ized thanks to @BigBlueHat so this should be an easy fix.

**Comment by BigBlueHat** [comment]
Thanks, @tilgovi :smile_cat: 

Do we have a conclusion on the mailing list link? It's an easy enough change of course.

**Comment by tilgovi** [comment]
I would privilege the okfn one but with a link to searchable archives at gmane.
