### ISSUE TITLE
Consolidate to Jekyll site?

### ISSUE THREAD

**Issue by BigBlueHat** [openannotation/annotatorjs.org#17]
Right now `master` and `gh-pages` aren't in sync. Since GitHub Pages can handle compiling Jekyll sites directly (post-push), I'd like to propose turning (and I'd be happy to do this!) the site into "just" a Jekyll site.

I'd use the Jekyll template already in use for the `_news` section (see `master`), make all the pages `_pages` content, and generally get things setup for simpler service.

Once complete, I'd propose dropping the `master` branch and making `gh-pages` the default / primary branch on the repo to avoid confusion later.

Give me a +1, and imma do it. :wink:

**Comment by tilgovi** [comment]
If there's nothing that requires user intervention in the build then that seems totally right.

**Comment by nickstenning** [comment]
Sounds good. 

It looks like we either didn't finish this properly or somebody has pushed master again after it was deleted. `gh-pages` is the default branch on this repository, and I would imagine the intent was to remove master as you describe.

**Comment by tilgovi** [comment]
I had written some nonsense about syncing master to gh-pages but I think it's clear a jekyll site would be much better.

**Comment by BigBlueHat** [comment]
I planned to tackle this one this week, but computer catastrophe's prevented that. :fire: :computer: :fire: :sob: 

It's on the :ambulance: though, so should be right as :umbrella: soon. :wink:

Stay tuned! :radio:
