### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by shaw2thefloor** [openannotation/annotatorjs.org#35]
Hi there. I want to use the event :

`annotationEditorShown(editor, annotation)`

but I don't think this is supported in the v2 alpha. Are there plans to make this available in the latest version?

**Comment by tilgovi** [comment]
There are not, but it should be fairly easy to implement yourself.

The `annotator.ui.main` function returns a block of hooks:

```js
    {
        // ... left out for brevity ...

        beforeAnnotationCreated: function (annotation) {
            // Editor#load returns a promise that is resolved if editing
            // completes, and rejected if editing is cancelled. We return it
            // here to "stall" the annotation process until the editing is
            // done.
            return s.editor.load(annotation, s.interactionPoint);
        },

        beforeAnnotationUpdated: function (annotation) {
            return s.editor.load(annotation, s.interactionPoint);
        }
    }
```

Instead, you can use something like this:

```js
function myAppExtension(options) {
  var hooks = annotator.ui.main(options);

  // We'll have to capture the default hooks. They have the reference
  // to the editor object and we do not, so we'll invoke them to show the
  // editor.
  var beforeAnnotationCreated = hooks.beforeAnnotationCreated;
  var beforeAnnotationUpdated = hooks.beforeAnnotationUpdated;

  hooks.beforeAnnotationCreated = function (annotation) {
    // Custom logic here, then either invoke or skip the base hook

    // Either invoke this, or not, as you wish, but if you do make sure to return the promise
    var promise = beforeAnnotationCreated(annotation);

    // Custom logic here, at which point the editor should be shown

    // You can attach more then clauses to the promise before you return it
    // if you want to take action after the editor is closed.
    return promise;
  }

  // Same thing for beforeAnnotationUpdated (left out for brevity)
}
```

**Comment by tilgovi** [comment]
In general, v2 is decomposed more into into components and you should feel free to use them as is, extend their hooks, or build a whole new application by copying the `annotator.ui.main` function and building your own.

I found that with the Annotator v1.2.x event model it was very difficult to change the way annotator behaved. It was possible to react to Annotator's events, but little else. With the promise-based hooks you can resolve asynchronous hooks to result values, defer resolution, or reject them. You have much more control, but fewer quick conveniences.
